services:
  jaeger:
    # image: jaegertracing/all-in-one:latest
    image: jaegertracing/all-in-one:1.29
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 16685:16685
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

  # migration creating random traces. Works only for jaeger:1.29
  pushtest:
    build:
      context: pushtest
      dockerfile: Dockerfile
    # command: ["php -r 'sleep(2);'", "&&", "php", "index.php"]
    entrypoint: ["sh", "entrypoint.sh"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
    depends_on:
      - jaeger